In [2]:
import numpy as np

def Vander_mat(arr,N,increasing = True):  
  if increasing == True:
    list_of_arr = [arr**i for i in range(N)]
  else:
    list_of_arr = [arr**(N-i-1) for i in range(N)]

  return np.stack(list_of_arr,1)


x = np.array([1,2,3,4])
print(Vander_mat(x,5))

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]]
